fid_b_size: 300
b_size : 2000
dataset: lsun

total_epochs: 5

g_model : 'sngan'
d_model : 'sngan'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
# use a single generator for all tests
d_path : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal/dcgan_kale_lsun/train/checkpoints_6961387/d_118715.pth'
g_path : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal/dcgan_kale_lsun/train/checkpoints_6961387/g_118715.pth'

#d_path : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal/sampling_lsun_4/tune_and_fids/checkpoints_1957158/d_best.pth'


log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp/neurips'
log_name : 'sampling_lsun_5'

penalty_type : 'gradient'
penalty_lambda : 1.

scheduler : 'ExponentialLR'
scheduler_gamma : 0.8
beta_1 : 0.5
beta_2 : 0.999

lr : 0.00001


# train
mode : fids
fid_samples : 50000

# sampling stuff
Z_dim : 100
sample_b_size : 2000




lmc_gamma : .01
lmc_kappa : .04
#latent_sampler : 'langevin'
num_lmc_steps : 1000
seed : 0
eval_fid : True
log_to_file : True
temperature : 100.