b_size: 128
dataset: cifar10

total_epochs: 100

g_model : 'dcgan'
d_model : 'dcgan'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
d_path : 'logs/dcgan/train/checkpoints/d_100.pth'
g_path : 'weights/dcgan/netG_epoch_199.pth'

log_dir : 'logs'
log_name : 'dcgan'

penalty_type : 'none'
with_fid : True

mode : eval
num_lmc_steps : 80

# sampling stuff
Z_dim : 100
bb_size : 1000

log_to_file : true

seed : 0


