b_size: 128
dataset: cifar10

total_epochs: 100

g_model : 'dcgan'
d_model : 'resnet-sn'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
# use a single generator for all tests
d_path : 'logs/resnet-sn_gp2-10/train/checkpoints/d_94.pth'
g_path : 'weights/dcgan/netG_epoch_199.pth'

log_dir : 'logs'
log_name : 'resnet-sn_gp2-10'

penalty_type : 'gradient2_l2'
penalty_lambda : 10
with_fid : True

gradient_clip_norm : 0

# train
mode : eval
# train_which : 'discriminator'

# sampling stuff
Z_dim : 100
sample_types : 'none,lmc'
bb_size : 1000
lmc_sample_size : 1

log_to_file : true



seed : 0


