b_size: 128
dataset: cifar10

total_epochs: 100

g_model : 'dcgan'
d_model : 'vanilla-no-sigmoid'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
# use a single generator for all tests
d_path : 'logs/vanilla-no-sigmoid_lr-0.01/checkpoints/d_32.pth'
g_path : 'weights/dcgan/netG_epoch_199.pth'

log_dir : 'logs_eval'
log_name : 'vanilla-no-sigmoid_gp-0.01_T-80'

penalty_type : gradient_l2
penalty_lambda : 0.01
with_fid : False

# train
mode : 'images'
# train_which : 'discriminator'

# sampling stuff
Z_dim : 100
sample_types : 'none,lmc'
lmc_sample_size : 20

#Z_folder : logs_eval/vanilla_gp-0.01/samples/
bb_size : 1000

log_to_file : False





