b_size: 128
dataset: cifar10

total_epochs: 100

g_model : 'dcgan'
d_model : 'vanilla'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
# use a single generator for all tests
d_path : 'logs/vanilla_lr-0.01/checkpoints/d_60.pth'
g_path : 'weights/dcgan/netG_epoch_199.pth'

log_dir : 'logs_eval'
log_name : 'vanilla_gp-0.01_T-80'

penalty_type : gradient_l2
penalty_lambda : 0.01
with_fid : True

# train
mode : 'eval'
# train_which : 'discriminator'

# sampling stuff
Z_dim : 100
sample_types : 'none,lmc'
lmc_steps : 80

#Z_folder : logs_eval/vanilla_gp-0.01/samples/Z_eval_eval_0.pkl
bb_size : 1000

log_to_file : True





