
b_size: 100
#dataset: redwine

dataset_type : UCI
trainer_type : ebm
total_epochs: 2000

log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp/neurips'
log_name : 'UCI'
optimizer: Adam

penalty_lambda : 0.1
penalty_type: 'gradient_l2'
scheduler : 'MultiStepLR'
use_scheduler : True
milestone : '50,500,750'


Z_factor : 20

penalty_g_lambda : 0.0001
lr : 0.0001
lr_generator : 0.0001


dis_bn : False
gen_bn : False

n_iter_d : 50

n_iter_d_init : 100

combined_discriminator : True

train_mode : 'both'
criterion : 'kale'


fid_mode : False

log_to_file : True

noise_factor : 20

initialize_log_partition : True

total_gen_iter : 1000