
b_size: 100
#dataset: redwine

dataset_type : UCI
trainer_type : ebm
total_epochs: 5000

log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp/neurips'
log_name : 'UCI'
optimizer: Adam

penalty_lambda : 0.0001
penalty_type: 'l2'
scheduler : 'MultiStepLR'
use_scheduler : True
milestone : '50,500,750'


Z_factor : 20

penalty_g_lambda : 0.0001
lr : 0.0001
lr_generator : 0.0001
#generator : 'maf'
#discriminator : 'maf'


#generator : 'made'
#discriminator : 'made'

dis_bn : False
gen_bn : False

n_iter_d : 50

combined_discriminator : True

train_mode : 'both'
criterion : 'cd'


fid_mode : False

log_to_file : True

noise_factor : 20

initialize_log_partition : True
