b_size: 1024
dataset: cifar10

total_epochs: 1000

log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal'
optimizer: Adam

criterion : 'kale'
data_name : 'redwine'
log_name : 'redwine_made'
problem : 'unconditional'
penalty_lambda : 0.1
penalty_type: 'gradient_l2'
scheduler : 'MultiStepLR'
Z_factor : 20
generator : 'made'
log_to_file : True
penalty_g_lambda : 0.00001
lr : 0.0001
g_path : '/nfs/gatsbystor/michaela/projects/kale/exp/uci_rebuttal/redwine/checkpoints/gen_999'




dis_bn : False
gen_bn : False
n_iter_d : 10
combined_discriminator : False

adversarial : True

likelihood_mode : False