b_size: 128
dataset: cifar10

total_epochs: 100

log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp'

optimizer: Adam




# For built-in data augmentation
criterion : 'kale'


# For data augmentation in classifier














