b_size: 128
dataset: cifar10

total_epochs: 21

gen_model : 'dcgan'
dis_model : 'vanilla'

log_dir : 'logs'
log_name : 'test'
optimizer: Adam


# For built-in data augmentation
criterion : 'kale'


d_path : 'weights/dcgan/netD_epoch_199'
g_path : 'weights/dcgan/netG_epoch_199'

# just gonna sample here
eval_pre_trained : False
Z_dim : 100

sample_type : 'none,lmc'

train_which : 'd'






