b_size: 128
dataset: cifar10

total_epochs: 100

log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp'
log_name : 'test_2'
optimizer: Adam




# For built-in data augmentation
criterion : 'logistic'


d_path : 'weights/dcgan/netD_epoch_199'

g_path : 'weights/dcgan/netG_epoch_199'

load_pre_trained : True
Z_dim : 100
model : 'dcgan'
# For data augmentation in classifier














