fid_b_size: 50
b_size : 100


total_epochs: 100

g_model : 'sngan'
d_model : 'sngan'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
g_path : 'logs/train/cifar10/checkpoints_00000/g_0000.pth'
d_path : 'logs/train/cifar10/checkpoints_00000/d_0000.pth'
log_dir : 'logs'
data_path : 'data/'

log_name : ''

penalty_type : 'gradient'
penalty_lambda : 1.

scheduler : 'ExponentialLR'
scheduler_gamma : 0.8
beta_1 : 0.5
beta_2 : 0.999

lr : 0.00001

with_fid : True

# train
mode : sample
fid_samples : 5000

# sampling stuff
Z_dim : 100
sample_b_size : 500




lmc_kappa : 100.
latent_sampler : 'langevin'
num_sampler_steps : 1000
seed : 0
eval_fid : True
log_to_file : False



