b_size: 128
dataset: cifar10

total_epochs: 100

g_model : 'dcgan'
d_model : 'spectral-dcgan'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
# use a single generator for all tests
# d_path : 'weights/dcgan/netD_epoch_199'
g_path : 'weights/dcgan/netG_epoch_199.pth'

log_dir : 'logs'
log_name : 'spectral-official_nobias'

penalty_type : gradient_l2
penalty_lambda : 0.0

# train
# eval_pre_trained : False
train_which : 'discriminator'

# sampling stuff
Z_dim : 100
sample_type : 'none,lmc'

log_to_file : true






