b_size: 128
dataset: cifar10

total_epochs: 200

g_model : 'dcgan'
#d_model : 'vanilla'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
d_path : 'logs/test_vanilla/checkpoints/d_10'
g_path : 'weights/dcgan/netG_epoch_199.pth'
# g_path : 'logs/test_vanilla/checkpoints/g_10'

# train
eval_pre_trained : True
# train_which : 'both'

# sampling stuff
Z_dim : 100
sample_type : 'none,lmc'








