b_size: 128
dataset: cifar10

total_epochs: 100

g_model : 'dcgan'
d_model : 'dcgan-sn'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
# use a single generator for all tests
d_path : 'logs/dcgan-sn_gp2-10_lr-2e5/train/checkpoints/d_90.pth'
g_path : 'weights/dcgan/netG_epoch_199.pth'

log_dir : 'logs'
log_name : 'dcgan-sn_gp2-10_lr-2e5'

penalty_type : gradient2_l2
penalty_lambda : 10
with_fid : True

lr : 0.00002

# train
mode : fids
# train_which : 'discriminator'

# sampling stuff
Z_dim : 100
sample_types : 'none,lmc'
bb_size : 1000
lmc_sample_size : 1

log_to_file : true



seed : 0


