b_size: 128
dataset: cifar10

total_epochs: 400

g_model : 'dcgan-sn'
d_model : 'dcgan-sn'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
# use a single generator for all tests
d_path : 'logs/BOTH/dcgan-sn,dcgan-sn_gp2-1_2/train/checkpoints/d_390.pth'
g_path : 'logs/BOTH/dcgan-sn,dcgan-sn_gp2-1_2/train/checkpoints/g_390.pth'

log_dir : 'logs/BOTH'
log_name : 'dcgan-sn,dcgan-sn_gp2-1_3'

penalty_type : 'gradient2_l2'
penalty_lambda : 1
with_fid : False

lr : 0.0001
lr_generator : 0.00002

# train
mode : train
train_which : 'both'

# sampling stuff
Z_dim : 100
sample_types : 'none,lmc'
bb_size : 50
lmc_sample_size : 20

log_to_file : true



seed : 0


