b_size: 128
dataset: cifar10
total_epochs: 100

g_model : 'dcgan-sn'
d_model : 'resnet-sn'

optimizer: Adam
criterion : 'kale'

# load pretrained weights
log_dir : 'logs'

penalty_type : 'gradient'
penalty_lambda : 1.0


# train
#mode : train
train_which : 'both'
with_fid : False

#use_scheduler : True

# sampling stuff
Z_dim : 100
bb_size : 1000

log_to_file : True

seed : 0
fid_samples : 50000

#latent_sampler : 'hmc'
bn : False
skipinit : False

lr : 0.0001
