b_size: 128
dataset: lsun
total_epochs: 100

g_model : 'dcgan'
d_model : 'resnet-sn'

optimizer: Adam
criterion : 'kale'

# load pretrained weights
g_path : 'weights/lsun/netG_epoch_10.pth'
log_dir : 'logs_lsun'

penalty_type : 'none'
penalty_lambda : 0.0

# train
#mode : train
train_which : 'discriminator'
with_fid : False

#use_scheduler : True

# sampling stuff
Z_dim : 100
bb_size : 1000

log_to_file : True

seed : 0
fid_samples : 50000

#latent_sampler : 'hmc'
bn : False
skipinit : False

lr : 0.00001
