b_size: 128
dataset: imagenet32
total_epochs: 2300

g_model : 'sngan'
#d_model : 'resnet-sn'
#d_model : 'resnet-sn'
d_model : 'sngan'

optimizer: Adam

criterion : 'kale'
num_workers : 4
# load pretrained weights
#g_path : ''
log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal'
log_name : 'sngan_imagenet'

imagenet_train_path: /nfs/gatsbystor/michaela/imagenet/imagenet32/out_data_train/
imagenet_test_path: /nfs/gatsbystor/michaela/imagenet/imagenet32/out_data_val/

d_path : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal/sngan_imagenet/train/checkpoints_7216626/d_18013.pth'
g_path : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal/sngan_imagenet/train/checkpoints_7216626/g_18013.pth'



penalty_type : 'gradient'
penalty_lambda : 1.

scheduler : 'ExponentialLR'
scheduler_gamma : 0.8
beta_1 : 0.5
beta_2 : 0.999


# train
#mode : train
train_which : 'both'
with_fid : True
n_iter_d_init : 10
#use_scheduler : True

# sampling stuff
Z_dim : 100
bb_size : 1000

log_to_file : True

seed : 0
fid_samples : 50000

#latent_sampler : 'hmc'
bn : False
skipinit : False

optimal_log_partition : True
lr_partition : 0.99

manual_update : False

lmc_gamma : 0.001

lr : 0.01
lr_generator : 0.0001
