b_size: 128
dataset: cifar10
total_epochs: 2300

g_model : 'sngan'
#d_model : 'resnet-sn'
#d_model : 'resnet-sn'
d_model : 'sngan'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
#g_path : ''
log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp/rebuttal'
#log_name : 'sampler'

penalty_type : 'gradient'
penalty_lambda : 1.

scheduler : 'ExponentialLR'
scheduler_gamma : 0.8
beta_1 : 0.5
beta_2 : 0.999


optimal_log_partition : True

# train
#mode : train
train_which : 'both'
with_fid : True

#use_scheduler : True

# sampling stuff
Z_dim : 100
bb_size : 1000

log_to_file : True

seed : 0
fid_samples : 50000

#latent_sampler : 'hmc'
bn : False
skipinit : False

lr_partition : 1.

lr : 0.0001

lr_generator : 0.0001
