b_size: 1000
dataset: lsun
total_epochs: 2300

g_model : 'sngan'
#d_model : 'resnet-sn'
#d_model : 'resnet-sn'
d_model : 'sngan'

optimizer: Adam

criterion : 'kale'

# load pretrained weights
#g_path : ''
log_dir : '/nfs/gatsbystor/michaela/projects/kale/exp/nips'
log_name : 'toy'
data_path: '/nfs/gatsbystor/michaela/projects/kale/data'
penalty_type : 'gradient'
penalty_lambda : .001

scheduler : 'ExponentialLR'
scheduler_gamma : 0.8
beta_1 : 0.5
beta_2 : 0.999


# train
#mode : train
train_mode : 'energy'
with_fid : True
trainer_type : 'toy'
dataset_type: 'toy'
discriminator : 'toy'
generator : 'toy'
#use_scheduler : True

# sampling stuff
Z_dim : 100
bb_size : 1000

log_to_file : False

seed : 0
fid_samples : 50000

#latent_sampler : 'hmc'
bn : False
skipinit : False

optimal_log_partition : True
lr_partition : 0.99
lr : 0.001
lr_generator : 0.0001
manual_update : False

n_iter_d_init : 500
n_iter_d : 20
temperature : 1.



